apiVersion: v1
kind: Pod
metadata:
  name: linux
  namespace: demok8s
spec:
  containers:
    - name: busybox
      image: busybox
      command:
        - sleep
        - "3600"
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500"
    - name: alpine
      image: alpine
      command:
        - sleep
        - "3600"
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500"